"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - FL1_joint
          - FL2_joint
          - FL3_joint
          - FR1_joint
          - FR2_joint
          - FR3_joint
          - RL1_joint
          - RL2_joint
          - RL3_joint
          - RR1_joint
          - RR2_joint
          - RR3_joint

      gains:
        FL1_joint : {p: 9, d: 0.3055, i: 0.03}
        FL2_joint : {p: 9, d: 0.3055, i: 0.03}
        FL3_joint : {p: 9, d: 0.3055, i: 0.03}
        FR1_joint : {p: 9, d: 0.3055, i: 0.03}
        FR2_joint : {p: 9, d: 0.3055, i: 0.03}
        FR3_joint : {p: 9, d: 0.3055, i: 0.03}
        RL1_joint : {p: 9, d: 0.3055, i: 0.03}
        RL2_joint : {p: 9, d: 0.3055, i: 0.03}
        RL3_joint : {p: 9, d: 0.3055, i: 0.03}
        RR1_joint : {p: 9, d: 0.3055, i: 0.03}
        RR2_joint : {p: 9, d: 0.3055, i: 0.03}
        RR3_joint : {p: 9, d: 0.3055, i: 0.03}